name: Azure Container Registry

on: [workflow_dispatch]

jobs:
  create-nginx-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the source code from the repository
      uses: actions/checkout@v4

    - name: Build image
      run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend:latest2 .

    - name: List images created
      run: docker images

    - name: Run Docker container
      run: docker run -d -p 8080:80 ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend:latest2

    #- name: Wait for container to start
    #  run: sleep 5  

    #- name: Test with curl
      #run: curl http://localhost:8080
    #  run: curl  http://localhost:8080/api/health

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Push image to Azure Container Registry  
      run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend:latest2
